PACKAGE_NAME="usbio"
PACKAGE_VERSION="0.1"

MAKE="make -C . KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C . clean"

BUILT_MODULE_NAME="usbio"
DEST_MODULE_LOCATION="/updates"

AUTOINSTALL="yes"
